CREATE TABLE `pkmodel`.`tpaper` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(500) NOT NULL,
  `AUTHOR` VARCHAR(500) NOT NULL,
  `PHUBLISHED` VARCHAR(500) NOT NULL,
  `YEAR` VARCHAR(45) NOT NULL,
  `MYNAME` VARCHAR(45) NULL,
  `NOFKEYS` INT NOT NULL,
  `COMMENT` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE `pkmodel`.`tterm` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAPER` VARCHAR(500) NOT NULL,
  `KEYWORD` VARCHAR(100) NOT NULL,
  `RELATIONSHIP` VARCHAR(45) NOT NULL,
  `VALUE` INT NOT NULL,
  `COMMENT` VARCHAR(500) NULL,
  PRIMARY KEY (`ID`));